import type { Metadata } from "next";
import logo from "../public/logo.png"
import "./globals.css";
import { Open_Sans } from "next/font/google"
import Head from "next/head";
const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={openSans.className}>{children}</body>
    </html>
  );
}
